App peliculas
brianwolf/app-movies-training pull request #3
Opened 2023-04-20 06:35 UTC by FrancisLuna

Se agrega la app de peliculas.

2023-04-20 06:38 UTC, FrancisLuna commented on apps/example/migrations/0002_genreentity.py
Upsi, se me escapo esto en el commit :/

2023-04-20 06:41 UTC, FrancisLuna commented on apps/peliculas/models.py
> +    def buscar_genero_en_DB(genero: Genero) -> "GeneroEntity":
Aca no se como pasarle que puede devolver un None sin que chille. -> "GeneroEntity" | None
No le gusta porque no puede hace un | entre un NoneType y un str. Si lo vuelvo str no le gusta que sea str|str ...

2023-04-20 11:37 UTC, alexiscaspell commented on apps/peliculas/models.py
> +    def buscar_genero_en_DB(genero: Genero) -> "GeneroEntity":
Con un Optional[GeneroEntity] probaste?

2023-04-20 11:39 UTC, alexiscaspell commented on apps/example/migrations/0002_genreentity.py
Yy bórralo .. , el pr se actualiza solito. Podes seguir modificando sobre el branch con el pr abierto

2023-04-20 11:42 UTC, alexiscaspell commented
> Se agrega la app de peliculas.

Acá si te interesa hacerlo lo más correcto posible, es buena práctica poner un listado de las funcionalidades que desarrollaste, tipo resumen. Y también se suele meter acá el link del tk de trello relacionado.

2023-04-20 14:42 UTC, FrancisLuna commented on apps/peliculas/models.py
> +    def buscar_genero_en_DB(genero: Genero) -> "GeneroEntity":
Ahi va, no  queria importar el Optional. Supuestamente python 3.10+ lo tenia ... pero ni idea porque chillaba

2023-04-20 18:34 UTC, alexiscaspell commented on apps/peliculas/models.py
> +        # TODO: como verga catcheo el: peliculas.models.GeneroEntity.DoesNotExist: GeneroEntity matching query does not exist. No puedo pasarle el argumento self
from django.core.exceptions import ObjectDoesNotExist

2023-04-20 18:36 UTC, alexiscaspell commented on apps/peliculas/models.py
> +    def extraer_nuevos_generos(self):
por ahi te conviene directamente llamarla nuevos_generos

2023-04-21 15:55 UTC, alexiscaspell commented on apps/peliculas/models.py
> +        # TODO: como verga catcheo el: peliculas.models.GeneroEntity.DoesNotExist: GeneroEntity matching query does not exist. No puedo pasarle el argumento self
viste si esto funca @FrancisLuna ?, supuestamente segun habia googleado esa excepcion contiene el DoesNotExist

2023-04-22 01:07 UTC, alexiscaspell commented on apps/peliculas/repository.py
> +        genero_entity = GeneroEntity.buscar_genero_en_DB(genero)
aca te quedaria mejor un GeneroEntity.get_by_nombre o como se llame el campo por el que buscas

2023-04-22 01:10 UTC, alexiscaspell commented on apps/peliculas/repository.py
> +        genero_entity = GeneroEntity.buscar_genero_en_DB(genero)
por ahi si es el objeto completo puede ser un get_by_object, no se no tengo mucha imaginacion con los nombres

2023-04-22 01:13 UTC, alexiscaspell commented on apps/peliculas/repository.py
> +        raise AppException(ExampleError.EXAMPLE_OBJECT_NOT_EXIST, msj)
Fijate si aca no queda mejor definir tu propia excepcion que herede de AppException, como PeliculaInexistenteException, o algo asi

2023-04-22 01:18 UTC, alexiscaspell commented on apps/peliculas/views.py
> +            return HttpResponse(status=204)
Esto es medio feucho porque deberia ser un error de negocio (409) o un recurso no encontrado (404), a lo sumo en el peor de los casos un 500. Pero un 204 le estas diciendo: "chabon, ta todo tranca aca pero no hay datos que retornar" y eso esta bien cuando haces una busqueda generica, como por nombre, genero,etc,  pero no cuando accedes por id, xq ahi quiere decir que el que te consulto te envio un id invalido (me entende?).

2023-04-22 01:21 UTC, alexiscaspell requested changes
fran primero revisa esas cositas, igual esta bastante bien el codigo, se entiende y se ve limpio. segui asi :)

2023-04-23 02:40 UTC, FabrizioDiPrinzio reviewed
Te deje unos comentarios. Algunas son sugerencias, otos son comenarios de cosas de django que pienso que te puedan ayudar, y oras son respuestas a tus preguntas.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/dto.py
> +    )
Esto podria hacerse con los [Serializers de DJango Rest Framework](https://www.django-rest-framework.org/api-guide/serializers/) para estandarizar como transformar los objetos  jsons y viceversa.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/error.py
> +    EXAMPLE_OBJECT_NOT_EXIST = 'EXAMPLE_OBJECT_NOT_EXIST'
¿Por que el `EXAMPLE_` aca? Yo se lo sacaria porque sino suen muy a demo.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/migrations/0002_cargar_generos_defecto.py
> +    operations = [migrations.RunPython(cargar_generos_default)]
el metodo `RunPython` puede recibir un segundo argumento, que es otra funcion que se ejecuta cuando se revierte la migracion. Eso te va a facilitar un monton la vida si estas desarrollando y te das cuenta que hay algo mal con la migracion porque podes volver para atras, hacer los cmabios en las tablas que necesites y volver a correr la migracion para adelante.

Por lo general recomiendo tratar de hacer que tus migraciones sean reversibles si podes porque te va a facilitar un monton la vida.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/models.py
> +        # TODO: como verga catcheo el: peliculas.models.GeneroEntity.DoesNotExist: GeneroEntity matching query does not exist. No puedo pasarle el argumento self
@FrancisLuna Proba con `@classmethod` en vez de `@staticmethod`. Los `classmethod` tambien son funciones de clase, pero reciben como argumento la propia clase, por lo cual podrias pasarle `cls.DoesNotExist` en teoria.

Por convencion a los`classmethod` se les pasa como primer parametro `cls` en vez de `self`

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/models.py
> +    def to_class(self) -> "Pelicula":
En python 3.11, tenes el [typinig.Self](https://peps.python.org/pep-0673/) que podes usar para decir  que un metodo devuelve una instancia de la propia clase. Para considerar si quieren hacer el upgrade para tener acceso a esa feature.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/repository.py
> +    return [pelicula.id for pelicula in search] if search.exists() else []
El ternario aca es redundante porque la comprehension ya devuelve una lista vacia si la query no devuelve ningun resultado.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/repository.py
> +    return search.get().to_class() if search.exists() else None
Aca podrias hacer simplemente un [PeliculaEntity.objects.filter(id=id).first()](https://peps.python.org/pep-0673/) que ya devuelve el primer resultado o `None` si nada matchea.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/repository.py
> +    pelicula_entity.save()
Si no queres que se guarde el objeto si algo se rompe, te conviene hacer el `.save()` al final de la funcion justo antes del return. Asi te aseguras que si hubo algun error antes no guardaste nada.

Tambien podes usar [transactions](https://docs.djangoproject.com/en/4.2/topics/db/transactions/#controlling-transactions-explicitly) que se rollbackean automatica si hay alguna excepcion entonces no guardan los cambios en la base de datos. Recomiendo siempre usar transaccciones cuando vas a tocar algo en la base de datos por las dudas.

2023-04-23 02:40 UTC, FabrizioDiPrinzio commented on apps/peliculas/views.py
> +            return HttpResponse(status=204)
cuando el objeto no existe eso siempre es un 404.

2023-04-28 03:40 UTC, FrancisLuna commented on apps/peliculas/models.py
> +        # TODO: como verga catcheo el: peliculas.models.GeneroEntity.DoesNotExist: GeneroEntity matching query does not exist. No puedo pasarle el argumento self
Se implenta con @classmethod. Gracias :D

2023-04-28 03:43 UTC, FrancisLuna commented on apps/peliculas/repository.py
> +        genero_entity = GeneroEntity.buscar_genero_en_DB(genero)
Se cambia a get_by_object.

2023-04-28 03:45 UTC, FrancisLuna commented on apps/peliculas/repository.py
> +        raise AppException(ExampleError.EXAMPLE_OBJECT_NOT_EXIST, msj)
@brianwolf si creo excepciones propias, donde las meto? en error.py?

2023-04-28 03:47 UTC, FrancisLuna commented on apps/peliculas/views.py
> +            return HttpResponse(status=204)
Se cambia a 404

2023-04-28 03:49 UTC, FrancisLuna commented on apps/peliculas/dto.py
> +    )
Gracias!!!!

2023-04-28 04:34 UTC, FrancisLuna commented on apps/peliculas/repository.py
> +        raise AppException(ExampleError.EXAMPLE_OBJECT_NOT_EXIST, msj)
Se deja como esta >D, alexis contesta jaja

2023-04-28 05:04 UTC, FrancisLuna commented on apps/peliculas/migrations/0002_cargar_generos_defecto.py
> +    operations = [migrations.RunPython(cargar_generos_default)]
Se agradece!

2023-04-28 06:21 UTC, alexiscaspell approved these changes

2023-04-28 06:23 UTC, merged